In [ ]:
#importing necessery libraries and reading the file
import pandas as pd
data=pd.read_excel('/content/Crime_Data.xlsx')
display(data)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,2001-08-27 23:00:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,...,NaN,NaN,26,1182305.0,1881212.0,2001,2015-08-17 15:03:40,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,2001-10-16 16:30:00,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,NaN,NaN,5,1174713.0,1861451.0,2001,2015-08-17 15:03:40,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,2001-09-29 05:35:00,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,...,NaN,NaN,08B,1151878.0,1920763.0,2001,2015-08-17 15:03:40,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,2001-09-12 09:05:00,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,...,NaN,NaN,7,1145544.0,1861043.0,2001,2015-08-17 15:03:40,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,2001-10-18 17:34:00,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,...,NaN,NaN,26,1140670.0,1902673.0,2001,2015-08-17 15:03:40,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date                  549999 non-null  datetime64[ns]
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  datetime64[ns]
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 85.0+ MB

In [ ]:
data['Location Description'].fillna('Unknown',inplace=True)

<ipython-input-26-33826d3eefc8>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Location Description'].fillna('Unknown',inplace=True)

In [ ]:
data.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description         0
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    336325
Community Area          334906
FBI Code                     0
X Coordinate              6912
Y Coordinate              6912
Year                         0
Updated On                   0
Latitude                  6912
Longitude                 6912
Location                  6912
dtype: int64

In [ ]:
blockcoordinates=data.groupby('Block')[['Latitude','Longitude']].first()
data['Latitude']=data['Latitude'].fillna(data['Block'].map(blockcoordinates['Latitude']))
data['Longitude']=data['Longitude'].fillna(data['Block'].map(blockcoordinates['Longitude']))

In [ ]:
data.drop(['Ward','Community Area'],axis=1,inplace=True)

In [ ]:
#data.drop('Updated On',axis=1,inplace=True)

In [ ]:
data.drop(['X Coordinate','Y Coordinate'],axis=1,inplace=True)

In [ ]:
data.isnull().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description       0
Arrest                     0
Domestic                   0
Beat                       0
District                   0
FBI Code                   0
Year                       0
Updated On                 0
Latitude                1477
Longitude               1477
Location                6912
dtype: int64

In [ ]:
data['Longitude']=data['Longitude'].fillna('Unknown')
data['Latitude']=data['Latitude'].fillna('Unknown')

In [ ]:
data.isnull().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description       0
Arrest                     0
Domestic                   0
Beat                       0
District                   0
FBI Code                   0
Year                       0
Updated On                 0
Latitude                   0
Longitude                  0
Location                6912
dtype: int64

In [ ]:
# Split the datetime64[ns] column into separate Date and Time columns
data['Case_Date'] = data['Date'].dt.date  # Extract only the date part
data['Case_Time'] = data['Date'].dt.time  # Extract only the time part

# Verify the result
print(data[['Date', 'Case_Date', 'Case_Time']].head())

                 Date   Case_Date Case_Time
0 2007-08-25 09:22:18  2007-08-25  09:22:18
1 2021-05-24 15:06:00  2021-05-24  15:06:00
2 2021-06-26 09:24:00  2021-06-26  09:24:00
3 2023-11-09 07:30:00  2023-11-09  07:30:00
4 2023-11-12 07:59:00  2023-11-12  07:59:00

In [ ]:
data['Location'] = data.apply(
    lambda row: f"({row['Latitude']}, {row['Longitude']})" if not pd.isna(row['Latitude']) and not pd.isna(row['Longitude']) else None,
    axis=1
)
data.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,FBI Code,Year,Updated On,Latitude,Longitude,Location,Case_Date,Case_Time
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,08A,2007,2015-08-17 15:03:40,42.017609,-87.671933,"(42.017608579, -87.671932599)",2007-08-25,09:22:18
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,01A,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)",2021-05-24,15:06:00
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,01A,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)",2021-06-26,09:24:00
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,5,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)",2023-11-09,07:30:00
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,08B,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)",2023-11-12,07:59:00

In [ ]:
data['Update_Date'] = data['Updated On'].dt.date  # Extract only the date part
data['Update_Time'] = data['Updated On'].dt.time  # Extract only the time part

# Verify the result
print(data[['Updated On', 'Update_Date', 'Update_Time']].head())

           Updated On Update_Date Update_Time
0 2015-08-17 15:03:40  2015-08-17    15:03:40
1 2023-11-18 15:39:49  2023-11-18    15:39:49
2 2023-11-18 15:39:49  2023-11-18    15:39:49
3 2023-11-18 15:39:49  2023-11-18    15:39:49
4 2023-12-09 15:41:24  2023-12-09    15:41:24

In [ ]:
data.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
FBI Code                0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
Case_Date               0
Case_Time               0
Update_Date             0
Update_Time             0
dtype: int64

In [ ]:
data.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,FBI Code,Year,Updated On,Latitude,Longitude,Location,Case_Date,Case_Time,Update_Date,Update_Time
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,08A,2007,2015-08-17 15:03:40,42.017609,-87.671933,"(42.017608579, -87.671932599)",2007-08-25,09:22:18,2015-08-17,15:03:40
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,01A,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)",2021-05-24,15:06:00,2023-11-18,15:39:49
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,01A,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)",2021-06-26,09:24:00,2023-11-18,15:39:49
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,5,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)",2023-11-09,07:30:00,2023-11-18,15:39:49
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,08B,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)",2023-11-12,07:59:00,2023-12-09,15:41:24

In [ ]:
data.shape

(549999, 22)

In [ ]:
cleaned_data=data[['ID','Case Number','Case_Date','Case_Time','Year','Block','IUCR','Primary Type','Description','Location Description','Arrest',	'Domestic','Beat','District','FBI Code','Update_Date','Update_Time','Latitude','Longitude','Location']]

In [ ]:
cleaned_data.head()

,ID,Case Number,Case_Date,Case_Time,Year,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,FBI Code,Update_Date,Update_Time,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25,09:22:18,2007,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,24,08A,2015-08-17,15:03:40,42.017609,-87.671933,"(42.017608579, -87.671932599)"
1,25953,JE240540,2021-05-24,15:06:00,2021,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,25,01A,2023-11-18,15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26,09:24:00,2021,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,17,01A,2023-11-18,15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09,07:30:00,2023,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1922,19,5,2023-11-18,15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12,07:59:00,2023,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,632,6,08B,2023-12-09,15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [ ]:
cleaned_data.to_csv('crime_cleaned.csv',index=False)